# Assignment#1, numpy methods and attributes

1 Import Numpy

In [1]:
import numpy as np

2 Print version location

In [4]:
print(np.version) #local address 

<module 'numpy.version' from 'C:\\Users\\Osman\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


3 Print version number

In [8]:
np.__version__ #

'1.19.2'

4 one Dimensional array with given range

In [9]:
arr=np.arange(10)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5 3x3 Boolean array with all elements be true

In [11]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

6 extracting odd numbers from an array

In [26]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[arr%2==1] #starting with 1, 

array([1, 3, 5, 7, 9])

7 convering 1D array to 2D array with 2 rows

In [33]:
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8 Stacking two arrays vertically

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [35]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9 getting common items between two numpy arrays

In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

10 get positions where elements of two arrays match

In [46]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

11 Print or show only 3 decimal places of the numpy array

In [51]:
rand_arr = np.random.random((5,3))

In [52]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.556, 0.392, 0.598],
       [0.087, 0.681, 0.921],
       [0.817, 0.003, 0.161],
       [0.75 , 0.049, 0.994]])

12 pretty print a numpy array by suppressing the scientific notation 

In [53]:
# Reset printoptions to default
np.set_printoptions(suppress=False)
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

13 limit the number of items printed in output of numpy array?
Difficulty Level: L1

In [54]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
#> array([ 0,  1,  2, ..., 12, 13, 14])

array([ 0,  1,  2, ..., 12, 13, 14])

14 array with all zeros in rows and columns

In [58]:
x=np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

15 array with all ones in rows and columns

In [59]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

16 new array of given shape and type, without initializing entries.

In [62]:
np.empty((7,7))

array([[1.247e-311, 1.247e-311, 1.691e-306, ..., 1.891e-307, 7.566e-307,
        3.115e-307],
       [1.246e-306, 8.901e-307, 9.346e-307, ..., 1.068e-306, 1.057e-307,
        1.057e-307],
       [1.224e-307, 1.391e-307, 1.001e-307, ..., 1.335e-307, 9.457e-308,
        1.168e-307],
       ...,
       [8.456e-307, 1.057e-307, 1.057e-307, ..., 1.335e-307, 8.456e-307,
        1.001e-307],
       [8.011e-307, 1.391e-307, 1.335e-307, ..., 8.456e-307, 9.791e-307,
        9.457e-308],
       [9.791e-307, 1.057e-307, 8.901e-308, ..., 1.424e-306, 1.885e+214,
        3.155e+180]])

17 Returns the indices that would sort an array

In [64]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

18 Copy of the array, cast to a specified type

In [66]:
x = np.array([1, 2, 2.5])
x.astype(int)

array([1, 2, 2])

19 10x10 random rows and columns

In [68]:
x=np.random.randn(10,10)

In [69]:
x

array([[ 1.689, -1.592, -0.11 , ..., -0.837, -1.051, -0.643],
       [-0.502, -3.001,  0.287, ..., -1.286, -0.626,  0.342],
       [-0.131, -1.092,  0.075, ...,  1.013, -0.838, -1.041],
       ...,
       [-0.976,  2.022, -0.513, ...,  1.116,  0.806,  1.568],
       [ 1.106,  0.182,  0.542, ..., -0.362, -1.005,  0.798],
       [ 0.288,  0.312, -2.357, ...,  0.758,  0.264,  0.314]])

20 square root

In [70]:
x=np.array([10,9,8,6,11])
np.sqrt(x)

array([3.162, 3.   , 2.828, 2.449, 3.317])

21 power

In [72]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

22 mean

In [73]:
x=np.array([10,9,7,10,7])

In [74]:
x.mean()

8.6

23 sum

In [76]:
x.sum()

43

24 cumulative product

In [77]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

25 cumulative product

In [92]:
x.cumprod()

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [93]:
y=x>6

26 True, False

In [84]:
y

array([ True,  True,  True,  True,  True])

27 any

In [87]:
y.any()

True

28 all

In [89]:
y.all()

True

29 unique

In [98]:
np.unique(x)

array([ 7,  9, 10])

30 transpose

In [101]:
x=np.random.randn(3,2)

In [102]:
x

array([[ 0.158,  0.515],
       [ 0.695,  0.165],
       [ 0.097, -1.376]])

In [103]:
x.transpose()

array([[ 0.158,  0.695,  0.097],
       [ 0.515,  0.165, -1.376]])

In [104]:
x=[[1,3,5],[7,9,0]]

In [105]:
arr1=np.array(x)

In [106]:
y=[[11,13,15],[17,19,10]]

In [107]:
arr2=np.array(y)

31 concatenate axis=0

In [108]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

32 concatenate axis=1

In [109]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

33 hstack

In [110]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

34 split

In [113]:
x=[1,4,5,6,7,9,1,4]

In [114]:
d=np.array(x)

In [115]:
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

35 prod

In [118]:
x=np.array([10,9,7,10,7])

In [119]:
x.prod()

44100

36 repeat

In [120]:
d=np.array([1,5,7,8])

In [121]:
np.repeat(d,3)

array([1, 1, 1, ..., 8, 8, 8])

37 tile

In [122]:
np.tile(d,2)

array([1, 5, 7, ..., 5, 7, 8])

In [123]:
stats=np.array([[1,2,3],[4,5,6]])

38 min

In [126]:
np.min(stats)

1

In [127]:
np.min(stats, axis=1)

array([1, 4])

In [128]:
np.min(stats, axis=0)

array([1, 2, 3])

39 max

In [130]:
np.max(stats)

6

In [131]:
np.max(stats, axis=1)

array([3, 6])

In [132]:
np.max(stats, axis=0)

array([4, 5, 6])

In [133]:
data=np.random.randn(2,3)

40 shape

In [135]:
data.shape

(2, 3)

41 type

In [137]:
data.dtype

dtype('float64')

In [139]:
arr = np.arange(10)

42 indexing

In [140]:
arr[5:8]

array([5, 6, 7])

In [142]:
arr[5:8]=12
arr

array([ 0,  1,  2, ..., 12,  8,  9])

43 slicing

In [145]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

44 fancy indexing

In [146]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       ...,
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [147]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [148]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

45 swapping

In [149]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [150]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

46 array

In [151]:
a = np.array([1, 2])

In [152]:
a

array([1, 2])

In [153]:
a.fill(0)
a

array([0, 0])

47 round

In [154]:
np.around([0.37, 1.64])

array([0., 2.])

48 std

In [155]:
a = np.array([[1, 2], [3, 4]])

In [156]:
np.std(a)

1.118033988749895

49 var

In [157]:
np.var(a)

1.25

50 diag

In [158]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
np.diag(x)

array([0, 4, 8])

51 strides

In [160]:
arr = np.arange(15) #generate a 2d matrix using strides, with a window length of 4 and strides of 2
arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [161]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])
print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


52 array sequence given only the starting point, length and the step

In [162]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)
seq(start, length, step)

array([ 5,  8, 11, ..., 26, 29, 32])